/* VOSPIROG — CATEGORY MENU / Cloudflare Pages */
(function(){'use strict';
var BREAKPOINT=1100;
var CATEGORIES=[{title:'Сытные пироги',target:'sit'},{title:'Сладкие пироги',target:'slad'},{title:'Пирожки',target:null},{title:'Десерты',target:null},{title:'Напитки',target:null}];
var state={menu:null,placeholder:null,items:[],sections:[],menuTop:0,menuHeight:64,isFixed:false,initialized:false,raf:0};
function y(){return window.pageYOffset||document.documentElement.scrollTop||0}
function target(id){if(!id)return null;var e=document.getElementById(id);if(!e){try{e=document.querySelector('[name="'+CSS.escape(id)+'"]')}catch(_){e=document.querySelector('[name="'+id+'"]')}}return e||null}
function active(item){state.items.forEach(function(x){x.classList.remove('is-active')});if(item)item.classList.add('is-active')}
function collect(){state.sections=[];state.items.forEach(function(item){var id=item.getAttribute('data-target');if(!id)return;var t=target(id);if(t)state.sections.push({item:item,target:t})})}
function spy(){if(!state.sections.length||!state.menu)return;var pos=y(),h=state.menu.offsetHeight||state.menuHeight,check=pos+h+80,current=state.sections[0];state.sections.forEach(function(s){var top=s.target.getBoundingClientRect().top+pos;if(top<=check)current=s});if(current)active(current.item)}
function clickItem(ev){var item=ev.currentTarget,id=item.getAttribute('data-target');if(!id)return;var t=target(id);if(!t){console.warn('VP MENU: не найден #'+id);return}ev.preventDefault();ev.stopPropagation();active(item);var top=t.getBoundingClientRect().top+y();var offset=(state.menu.offsetHeight||state.menuHeight)+20;window.scrollTo({top:Math.max(0,top-offset),behavior:'smooth'})}
function create(){var old=document.querySelector('.vp-category-menu');if(old)return old;var menu=document.createElement('div');menu.className='vp-category-menu';menu.setAttribute('data-vp-cloudflare-menu','1');var inner=document.createElement('div');inner.className='vp-category-menu__inner';CATEGORIES.forEach(function(cat,i){var b=document.createElement('button');b.type='button';b.className='vp-category-menu__item'+(i===0?' is-active':'');if(cat.target)b.setAttribute('data-target',cat.target);b.textContent=cat.title;inner.appendChild(b)});menu.appendChild(inner);var sit=document.getElementById('sit');if(sit&&sit.parentNode)sit.parentNode.insertBefore(menu,sit);else{var ar=document.getElementById('allrecords');if(ar)ar.insertBefore(menu,ar.firstChild);else document.body.insertBefore(menu,document.body.firstChild)}return menu}
function recalc(){if(!state.menu||state.isFixed)return;state.menuTop=state.menu.getBoundingClientRect().top+y();state.menuHeight=state.menu.offsetHeight||64;if(state.placeholder)state.placeholder.style.height=state.menuHeight+'px'}
function unfix(){if(!state.menu)return;state.isFixed=false;state.menu.classList.remove('vp-menu-fixed');if(state.placeholder){state.placeholder.classList.remove('vp-placeholder-active');state.placeholder.style.height='0px'}}
function sticky(){if(!state.menu)return;if(innerWidth<BREAKPOINT){unfix();return}if(y()>=state.menuTop&&!state.isFixed){state.isFixed=true;state.menuHeight=state.menu.offsetHeight||64;if(state.placeholder){state.placeholder.style.height=state.menuHeight+'px';state.placeholder.classList.add('vp-placeholder-active')}state.menu.classList.add('vp-menu-fixed')}else if(y()<state.menuTop&&state.isFixed)unfix()}
function schedule(){if(state.raf)return;state.raf=requestAnimationFrame(function(){state.raf=0;sticky();spy()})}
function bind(){state.items.forEach(function(item){if(item.getAttribute('data-vp-bound')==='1')return;item.setAttribute('data-vp-bound','1');item.addEventListener('click',clickItem)});window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',function(){unfix();setTimeout(function(){recalc();collect();sticky();spy()},0)},{passive:true})}
function init(){if(state.initialized)return;var menu=create();if(!menu)return;state.menu=menu;state.placeholder=document.createElement('div');state.placeholder.className='vp-menu-placeholder';menu.parentNode.insertBefore(state.placeholder,menu);state.items=Array.prototype.slice.call(menu.querySelectorAll('.vp-category-menu__item'));collect();recalc();bind();sticky();spy();state.initialized=true}
function start(){init();[300,800,1500,2500].forEach(function(d){setTimeout(function(){if(!state.initialized)init();collect();recalc();sticky();spy()},d)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
